# 4.6 GPU计算

In [1]:
!nvidia-smi # 对Linux/macOS用户有效

/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Sun Jan 21 20:50:47 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.04              Driver Version: 546.17       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060 ...    On  | 00000000:01:00.0  On |                  N/A |
| N/A   43C    P8              13W /  86W |    876MiB /  6144MiB |     28%      Default |
|                                         |                      |                  

In [2]:
import torch
from torch import nn

print(torch.__version__)

2.1.0+cu121


## 4.6.1 计算设备

In [3]:
torch.cuda.is_available() # cuda是否可用

True

In [4]:
torch.cuda.device_count() # gpu数量

1

In [5]:
torch.cuda.current_device() # 当前设备索引, 从0开始

0

In [6]:
torch.cuda.get_device_name(0) # 返回gpu名字

'NVIDIA GeForce RTX 3060 Laptop GPU'

## 4.6.2 `Tensor`的GPU计算

In [7]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [8]:
x = x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

In [9]:
x.device

device(type='cuda', index=0)

In [10]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([1, 2, 3], device=device)
# or
x = torch.tensor([1, 2, 3]).to(device)
x

tensor([1, 2, 3], device='cuda:0')

In [11]:
y = x**2
y

tensor([1, 4, 9], device='cuda:0')

In [12]:
# z = y + x.cpu()

## 4.6.3 模型的GPU计算

In [13]:
net = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

In [14]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)

In [15]:
x = torch.rand(2,3).cuda()
net(x)

tensor([[0.3578],
        [0.2525]], device='cuda:0', grad_fn=<AddmmBackward0>)